using AgentUI.Models;
using AgentUI.Services;
using Moq;

namespace AgentUI.Tests.ViewModels;

/// <summary>
/// Unit tests for BacklogViewModel business logic.
///
/// NOTE: These tests cover the pure C# logic (filters, counts, form validation).
/// Tests that exercise MainThread.BeginInvokeOnMainThread or other MAUI platform
/// types must be run on a device/simulator via the MAUI test runner.
/// </summary>
public class BacklogViewModelTests
{
    private static List<BacklogTask> MakeTasks() => new()
    {
        new() { Title = "Fix login bug",   Priority = TaskPriority.P1, Status = BacklogTaskStatus.Pending    },
        new() { Title = "Add dark mode",   Priority = TaskPriority.P2, Status = BacklogTaskStatus.InProgress },
        new() { Title = "Write API docs",  Priority = TaskPriority.P3, Status = BacklogTaskStatus.Completed  },
        new() { Title = "Blocked by infra",Priority = TaskPriority.P2, Status = BacklogTaskStatus.Blocked    },
        new() { Title = "Refactor auth",   Priority = TaskPriority.P1, Status = BacklogTaskStatus.Pending    },
    };

    // -------------------------------------------------------------------------
    // Model: BacklogTask defaults
    // -------------------------------------------------------------------------

    [Fact]
    public void BacklogTask_DefaultStatus_IsPending()
    {
        var task = new BacklogTask { Title = "Test task" };
        Assert.Equal(BacklogTaskStatus.Pending, task.Status);
    }

    [Fact]
    public void BacklogTask_DefaultPriority_IsP2()
    {
        var task = new BacklogTask { Title = "Test task" };
        Assert.Equal(TaskPriority.P2, task.Priority);
    }

    [Fact]
    public void BacklogTask_IdIsAutoGenerated_AndNonEmpty()
    {
        var t1 = new BacklogTask { Title = "A" };
        var t2 = new BacklogTask { Title = "B" };
        Assert.NotEmpty(t1.Id);
        Assert.NotEqual(t1.Id, t2.Id);
    }

    // -------------------------------------------------------------------------
    // Filter logic (extracted from BacklogViewModel.ApplyFilter)
    // -------------------------------------------------------------------------

    private static IEnumerable<BacklogTask> ApplyFilter(IEnumerable<BacklogTask> tasks, string filter) =>
        filter switch
        {
            "In Progress" => tasks.Where(t => t.Status == BacklogTaskStatus.InProgress),
            "Pending"     => tasks.Where(t => t.Status == BacklogTaskStatus.Pending),
            "Completed"   => tasks.Where(t => t.Status == BacklogTaskStatus.Completed),
            "Blocked"     => tasks.Where(t => t.Status == BacklogTaskStatus.Blocked),
            "P1"          => tasks.Where(t => t.Priority == TaskPriority.P1),
            "P2"          => tasks.Where(t => t.Priority == TaskPriority.P2),
            "P3"          => tasks.Where(t => t.Priority == TaskPriority.P3),
            _             => tasks
        };

    [Theory]
    [InlineData("All",         5)]
    [InlineData("Pending",     2)]
    [InlineData("In Progress", 1)]
    [InlineData("Completed",   1)]
    [InlineData("Blocked",     1)]
    [InlineData("P1",          2)]
    [InlineData("P2",          2)]
    [InlineData("P3",          1)]
    public void ApplyFilter_ReturnsCorrectCount(string filter, int expectedCount)
    {
        var tasks = MakeTasks();
        var result = ApplyFilter(tasks, filter).ToList();
        Assert.Equal(expectedCount, result.Count);
    }

    [Fact]
    public void ApplyFilter_UnknownFilter_ReturnsAll()
    {
        var tasks = MakeTasks();
        var result = ApplyFilter(tasks, "nonexistent").ToList();
        Assert.Equal(tasks.Count, result.Count);
    }

    // -------------------------------------------------------------------------
    // Count calculations (mirrors LoadTasksAsync body)
    // -------------------------------------------------------------------------

    [Fact]
    public void TaskCounts_AreComputedCorrectly()
    {
        var tasks = MakeTasks();
        var completed  = tasks.Count(t => t.Status == BacklogTaskStatus.Completed);
        var inProgress = tasks.Count(t => t.Status == BacklogTaskStatus.InProgress);
        var pending    = tasks.Count(t => t.Status == BacklogTaskStatus.Pending);
        var blocked    = tasks.Count(t => t.Status == BacklogTaskStatus.Blocked);

        Assert.Equal(1, completed);
        Assert.Equal(1, inProgress);
        Assert.Equal(2, pending);
        Assert.Equal(1, blocked);
        Assert.Equal(5, tasks.Count);
    }

    // -------------------------------------------------------------------------
    // CreateTask validation: empty title should produce an error message
    // -------------------------------------------------------------------------

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    public void CreateTask_EmptyTitle_SetsErrorStatusMessage(string title)
    {
        // Mirror the validation logic from CreateTaskAsync
        var statusMessage = string.IsNullOrWhiteSpace(title) ? "Title is required" : string.Empty;
        Assert.Equal("Title is required", statusMessage);
    }

    [Fact]
    public void CreateTask_ValidTitle_ProducesNoValidationError()
    {
        const string title = "Write unit tests";
        var statusMessage = string.IsNullOrWhiteSpace(title) ? "Title is required" : string.Empty;
        Assert.Empty(statusMessage);
    }

    // -------------------------------------------------------------------------
    // Priority mapping (mirrors CreateTaskAsync switch expression)
    // -------------------------------------------------------------------------

    [Theory]
    [InlineData("P1", TaskPriority.P1)]
    [InlineData("P2", TaskPriority.P2)]
    [InlineData("P3", TaskPriority.P3)]
    [InlineData("??", TaskPriority.P2)] // unknown defaults to P2
    public void PriorityMapping_IsCorrect(string raw, TaskPriority expected)
    {
        var result = raw switch
        {
            "P1" => TaskPriority.P1,
            "P3" => TaskPriority.P3,
            _    => TaskPriority.P2,
        };
        Assert.Equal(expected, result);
    }

    // -------------------------------------------------------------------------
    // IBacklogService mock: verify AddTaskAsync is called with correct data
    // -------------------------------------------------------------------------

    [Fact]
    public async Task CreateTask_CallsAddTaskAsync_WithCorrectTitle()
    {
        var mockService = new Mock<IBacklogService>();
        mockService.Setup(s => s.GetTasksAsync()).ReturnsAsync(new List<BacklogTask>());
        mockService.Setup(s => s.AddTaskAsync(It.IsAny<BacklogTask>())).Returns(Task.CompletedTask);

        BacklogTask? captured = null;
        mockService
            .Setup(s => s.AddTaskAsync(It.IsAny<BacklogTask>()))
            .Callback<BacklogTask>(t => captured = t)
            .Returns(Task.CompletedTask);

        var task = new BacklogTask
        {
            Title = "My new task",
            Priority = TaskPriority.P1,
            Status = BacklogTaskStatus.Pending,
        };
        await mockService.Object.AddTaskAsync(task);

        Assert.NotNull(captured);
        Assert.Equal("My new task", captured!.Title);
        Assert.Equal(TaskPriority.P1, captured.Priority);
    }
}
